controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:
      ru: '' # don't prefix URLs, the default locale
      en: '/en'

kernel:
    resource: ../src/Kernel.php
    type: annotation
